### ISSUE TITLE
error in running train_gnns.py file

### ISSUE THREAD

**Issue by Usama113** [ShichangZh/GStarX#2]
Hi, I tried to execute this command: `python train_gnns.py datasets=ba_2motifs models=gcn` and I got the following error:
```Error executing job with overrides: ['datasets=ba_2motifs', 'models=gcn']
Traceback (most recent call last):
  File "train_gnns.py", line 262, in main
    trainer.train(train_params=train_params, optimizer_params=optimizer_params)
  File "train_gnns.py", line 146, in train
    loss = self._train_batch(batch, batch.y)
  File "train_gnns.py", line 47, in _train_batch
    logits = self.model(data=data)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/notebooks/external_src/GStarX/gnnNets.py", line 359, in forward
    emb = self.get_emb(*args, **kwargs)
  File "/workspace/notebooks/external_src/GStarX/gnnNets.py", line 348, in get_emb
    x = self.convs[i](x, edge_index)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/notebooks/external_src/GStarX/gnnNets.py", line 258, in forward
    x = torch.matmul(x, self.weight)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1178, in __getattr__
    type(self).__name__, name))
AttributeError: 'GCNConv' object has no attribute 'weight'
```
What can i do to fix it. Thanks in advance.

**Comment by ShichangZh** [comment]
This looks like a PyG error. Can you check your PyG version please? The train_gnn.py script is adapted from the version of DIG that builds up on PyG 1.7.2. Recently, PyG updated to 2.0, which has changed a lot from PyG 1.X

The DIG it is adapted from: https://github.com/divelab/DIG/tree/dig/benchmarks/xgraph

**Comment by ShichangZh** [comment]
Recently I am a bit busy with other stuff. I will find a time to make the model to be compatible with PyG 2.0

**Comment by Usama113** [comment]
yes,using PyG 1.7.2 solves the issue. I assumed it is mentioned in requirements.txt. I would very much appreciate if you could provide the code working with PyG 2.0. Thanks a lot for your help.
